version: '3.8'

services:
  app:
    image: angocare:latest
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=angocare
      - DB_USERNAME=root
      - DB_PASSWORD=root

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: angocare
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
