version: '3.8'

services:
  app:
    image: $DOCKER_USERNAME/angocare:latest
    ports:
      - "80:80"
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=angocare
      - DB_USERNAME=root
      - DB_PASSWORD=root

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: angocare
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
