name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: angocare
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Instalar dependências
      run: npm install

    - name: Executar testes
      run: npm test

    - name: Configurar PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Instalar dependências PHP
      run: composer install

    - name: Criar arquivo .env
      run: |
        echo "APP_NAME=Laravel" > .env
        echo "APP_ENV=local" >> .env
        echo "APP_KEY=" >> .env
        echo "APP_DEBUG=true" >> .env
        echo "APP_URL=http://localhost" >> .env
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=angocare" >> .env
        echo "DB_USERNAME=root" >> .env
        echo "DB_PASSWORD=root" >> .env
        php artisan key:generate

    - name: Executar migrações
      run: php artisan migrate

    - name: Executar testes PHP
      run: php artisan test

    - name: Construir imagem Docker
      run: docker build -t angocare:latest .

    - name: Fazer login no Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Configurar Git
      run: |
        git config --global user.email "panzopedro26@gmail.com"
        git config --global user.name "panzo11"

    - name: Criar e enviar tag
      uses: phish108/autotag-action@v1.1.55
      with:
        github-token: ${{ secrets.MY_GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Inicializar Docker Swarm
      run: docker swarm init || docker swarm join --token SWMTKN-1-4ib0mp3wa4i87mlxx0706m5t4afi3bedfl0sc5p7n4yvr1xepx-3wp8rmj58f5lfnk1i0iexe4n5 192.168.221.88:2377

    - name: Deploy no Docker Swarm
      run: |
        docker stack deploy --compose-file docker-compose.yml angocare --with-registry-auth

    - name: Notificar Portainer
      run: |
        curl -X POST -H "Authorization: Bearer ${{ secrets.PORTAINER_API_TOKEN }}" \
        -H "Content-Type: application/json" \
        -d '{"type": "stack", "method": "git", "endpointId": 1, "repositoryUrl": "https://github.com/panzo11/ANGOCARE.git", "stackFile": "docker-compose.yml", "env": []}' \
        http://localhost:9000/api/stacks

  proxy_manager:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configurar Docker Compose
      run: |
        docker-compose -f docker-compose.proxy.yml up -d
